### ISSUE TITLE
Unable to compile with FFmepg 3.4.8 - Ubuntu Bionic

### ISSUE THREAD

**Issue by theofficialgman** [mickelson/attract#713]
Running this on nvidia jetson, I am unable to compile due to these recent changes:
https://github.com/mickelson/attract/commit/1b933c39dbd9201b09140e922babe21939d64dad

resulting in these errors on compilation. cmake passes and is higher than the required version:
```
src/media.cpp: In member function ‘void FeVideoImp::video_thread()’:
src/media.cpp:855:71: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
  FeDebug() << "End Video Thread - " << m_parent->m_imp->m_format_ctx->url << std::endl
                                                                       ^~~
src/media.cpp: In member function ‘bool FeMedia::open(const string&, const string&, sf::Texture*)’:
src/media.cpp:1070:30: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
      << m_imp->m_format_ctx->url << std::endl;
                              ^~~
src/media.cpp:1095:31: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
       << m_imp->m_format_ctx->url << std::endl;
                               ^~~
src/media.cpp:1144:29: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
     << m_imp->m_format_ctx->url << std::endl;
                             ^~~
src/media.cpp:1179:32: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
        << m_imp->m_format_ctx->url << std::endl;
                                ^~~
src/media.cpp:1194:32: error: ‘AVFormatContext {aka struct AVFormatContext}’ has no member named ‘url’
        << m_imp->m_format_ctx->url << std::endl;
                                ^~~
Makefile:524: recipe for target 'obj/media.o' failed
make: *** [obj/media.o] Error 1
```

**Comment by theofficialgman** [comment]
@mickelson can with put this behind case statements or something so it can still be compiled on systems with older ffmpeg?

**Comment by theofficialgman** [comment]
yup, fixed. thank you!
